import{S as y,i as l}from"./assets/vendor-9310f15c.js";(function(){const r=document.createElement("link").relList;if(r&&r.supports&&r.supports("modulepreload"))return;for(const e of document.querySelectorAll('link[rel="modulepreload"]'))a(e);new MutationObserver(e=>{for(const o of e)if(o.type==="childList")for(const c of o.addedNodes)c.tagName==="LINK"&&c.rel==="modulepreload"&&a(c)}).observe(document,{childList:!0,subtree:!0});function s(e){const o={};return e.integrity&&(o.integrity=e.integrity),e.referrerpolicy&&(o.referrerPolicy=e.referrerpolicy),e.crossorigin==="use-credentials"?o.credentials="include":e.crossorigin==="anonymous"?o.credentials="omit":o.credentials="same-origin",o}function a(e){if(e.ep)return;e.ep=!0;const o=s(e);fetch(e.href,o)}})();const L=document.querySelector(".gallery");function d(t){const r=t.reduce((s,a)=>s+`<li class="gallery-item">
              <a href=${a.largeImageURL}> 
              <img class="gallery-img" src =${a.webformatURL} alt=${a.tags}/>
              </a>
              <div class="gallery-text-box">
                <p>Likes: <span class="text-value">${a.likes}</span></p>
                <p>views: <span class="text-value">${a.views}</span></p>
                <p>comments: <span class="text-value">${a.comments}</span></p>
                <p>downloads: <span class="text-value">${a.downloads}</span></p>
              </div>
          </li>`,"");L.insertAdjacentHTML("beforeend",r)}function u(t){return axios.get(`https://pixabay.com/api/?${t}`)}const b=document.querySelector(".form"),m=document.querySelector(".gallery"),p=document.querySelector(".loader"),i=document.querySelector('[data-action="load-more"]'),n={key:"12371278-ee82e7e687c0227bfbef9a885",q:"",image_type:"photo",orientation:"horizontal",safesearch:!0,per_page:"15",page:"1"},f=new y(".gallery a",{nav:!0,captionDelay:250,captionsData:"alt",close:!0,enableKeyboard:!0,docClose:!0});function v(){m.innerHTML=""}function g(){p.style.display="block"}function h(){p.style.display="none"}function w(){const t=m.firstElementChild.getBoundingClientRect().height;window.scrollBy({top:5*t,behavior:"smooth"})}async function S(t){return await u(t).then(({data:r})=>{let{hits:s}=r;s.length<=0?l.error({position:"topRight",message:"Sorry, there are no images matching your search query. Please try again!"}):(n.page=1,d(s),f.refresh())}).catch(r=>{l.error({position:"topRight",message:`Sorry there was an error: ${r}`})}).finally(()=>{h()})}b.addEventListener("submit",t=>{t.preventDefault(),i.classList.add("is-hidden"),v(),g(),n.q=t.target.elements.search.value.trim();const r=new URLSearchParams(n);S(r),i.classList.remove("is-hidden"),t.currentTarget.reset()});i.addEventListener("click",async t=>{n.page++,n.q,g();const r=new URLSearchParams(n);await u(r).then(({data:s})=>{let{hits:a,totalHits:e}=s;Math.ceil(e/15)===n.page?(i.classList.add("is-hidden"),l.error({position:"topRight",message:"We're sorry, but you've reached the end of search results."})):(d(a),f.refresh())}).catch(s=>{l.error({position:"topRight",message:`Sorry there was an error: ${s}`})}).finally(()=>{w(),h()})});
//# sourceMappingURL=commonHelpers.js.map
