import{S as y,i as l}from"./assets/vendor-9310f15c.js";(function(){const o=document.createElement("link").relList;if(o&&o.supports&&o.supports("modulepreload"))return;for(const e of document.querySelectorAll('link[rel="modulepreload"]'))t(e);new MutationObserver(e=>{for(const a of e)if(a.type==="childList")for(const c of a.addedNodes)c.tagName==="LINK"&&c.rel==="modulepreload"&&t(c)}).observe(document,{childList:!0,subtree:!0});function s(e){const a={};return e.integrity&&(a.integrity=e.integrity),e.referrerpolicy&&(a.referrerPolicy=e.referrerpolicy),e.crossorigin==="use-credentials"?a.credentials="include":e.crossorigin==="anonymous"?a.credentials="omit":a.credentials="same-origin",a}function t(e){if(e.ep)return;e.ep=!0;const a=s(e);fetch(e.href,a)}})();const L=document.querySelector(".gallery");function u(r){const o=r.reduce((s,t)=>s+`<li class="gallery-item">
              <a href=${t.largeImageURL}> 
              <img class="gallery-img" src =${t.webformatURL} alt=${t.tags}/>
              </a>
              <div class="gallery-text-box">
                <p>Likes: <span class="text-value">${t.likes}</span></p>
                <p>views: <span class="text-value">${t.views}</span></p>
                <p>comments: <span class="text-value">${t.comments}</span></p>
                <p>downloads: <span class="text-value">${t.downloads}</span></p>
              </div>
          </li>`,"");L.insertAdjacentHTML("beforeend",o)}function p(r){return axios.get(`https://pixabay.com/api/?${r}`)}const b=document.querySelector(".form"),m=document.querySelector(".gallery"),g=document.querySelector(".loader"),i=document.querySelector('[data-action="load-more"]'),n={key:"12371278-ee82e7e687c0227bfbef9a885",q:"",image_type:"photo",orientation:"horizontal",safesearch:!0,per_page:15,page:1},f=new y(".gallery a",{nav:!0,captionDelay:250,captionsData:"alt",close:!0,enableKeyboard:!0,docClose:!0});function v(){m.innerHTML=""}function d(){g.style.display="block"}function h(){g.style.display="none"}function w(){const r=m.firstElementChild.getBoundingClientRect().height;window.scrollBy({top:2*r,behavior:"smooth"})}async function S(r){try{d();const{data:o}=await p(r);let{hits:s}=o;s.length===0?l.error({position:"topRight",message:"Sorry, there are no images matching your search query. Please try again!"}):(n.page=1,u(s),i.classList.remove("is-hidden"),f.refresh())}catch(o){l.error({position:"topRight",message:`Sorry there was an error: ${o}`})}finally{h()}}b.addEventListener("submit",r=>{r.preventDefault(),n.page=1,i.classList.add("is-hidden"),v(),d(),n.q=r.target.elements.search.value.trim();const o=new URLSearchParams(n);S(o),r.currentTarget.reset()});i.addEventListener("click",async r=>{n.page++,n.q,d();const o=new URLSearchParams(n);try{const{data:s}=await p(o);let{hits:t,totalHits:e}=s,a=Math.ceil(e/15);t.length===0||a===n.page?(i.classList.add("is-hidden"),t.length===0?l.error({position:"topRight",message:"We're sorry, but no results were found."}):l.error({position:"topRight",message:"We're sorry, but you've reached the end of search results."})):(u(t),f.refresh())}catch(s){l.error({position:"topRight",message:`Sorry there was an error: ${s}`})}finally{w(),h()}});
//# sourceMappingURL=commonHelpers.js.map
